dependencies:
- name: infrastructure
  repository: https://kaimeng.github.io/helm-repo
  version: 0.0.1-SS
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 1.1.12
- name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 1.1.10
  condition: activiti-cloud-modeling.enabled,modeling.enabled
- name: sample-runtime-bundle
  repository: https://kaimeng.github.io/helm-repo/
  version: 0.1.0
- name: sample-cloud-connector
  repository: https://kaimeng.github.io/helm-repo/
  version: 0.1.0
