apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if include "common.registry-pull-secrets" . }}
      imagePullSecrets:
      {{- include "common.registry-pull-secrets" . | indent 6 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}-backend
        image: {{ include "activiti-cloud-modeling.container-backend-image" . | quote }}
        imagePullPolicy: {{ tpl .Values.backend.image.pullPolicy . }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx{{ .Values.backend.javaOpts.xmx }} -Xms{{ .Values.backend.javaOpts.xms }} {{ .Values.backend.javaOpts.other}}"
        - name: SPRING_APPLICATION_NAME
{{- if .Values.service.name }}
          value: {{ .Values.service.name }}-backend
{{- else }}
          value: {{ template "fullname" . }}-backend
{{- end }}
        - name: SERVER_PORT
          value: "{{ .Values.service.backend.internalPort }}"
        - name: ACT_KEYCLOAK_URL
          value: {{ include "common.keycloak-url" . | quote }}
        - name: ACT_KEYCLOAK_REALM
          value: {{ include "common.keycloak-realm" . | quote }}
        - name: ACT_KEYCLOAK_RESOURCE
          value: {{ include "common.keycloak-resource" . | quote }}
        - name: ACTIVITI_CLOUD_MODELING_URL
          value: "localhost:{{ .Values.service.backend.internalPort }}"
{{ include "activiti-cloud-modeling.extra-env-backend" . | indent 8 }}
        ports:
        - containerPort: {{ .Values.service.backend.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ tpl .Values.backend.probePath . }}
            port: {{ .Values.service.backend.internalPort }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.backend.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ tpl .Values.backend.probePath . }}
            port: {{ .Values.service.backend.internalPort }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.backend.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
{{- if .Values.extraVolumeMounts }}
        volumeMounts:
{{- with .Values.extraVolumeMounts }}
{{ tpl . $ | indent 10 }}
{{- end }}
{{- end }}
      - name: {{ .Chart.Name }}
        image: {{ include "activiti-cloud-modeling.container-frontend-image" . | quote }}
        imagePullPolicy: {{ tpl .Values.frontend.image.pullPolicy . }}
        env:
        - name: APP_CONFIG_OAUTH2_HOST
          value: {{ include "common.keycloak-url" . }}/realms/{{ include "common.keycloak-realm" . }}
        - name: APP_CONFIG_OAUTH2_CLIENTID
          value: {{ include "common.keycloak-client" .| quote }}
        - name: APP_CONFIG_BPM_HOST
{{- if .Values.backend.url }}
          value: {{ tpl .Values.backend.url .|quote }}
{{- else }}
          value: {{ tpl (printf "%s/%s"  (include "common.gateway-url" .) .Values.backend.prefix) .|quote }}
{{- end }}
{{- if .Values.frontend.basepath }}
        - name: BASE_PATH
          value: "/{{ tpl .Values.frontend.basepath .}}/"
        - name: APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI
          value: "{{ include "common.gateway-url" . }}/{{ .Values.frontend.basepath }}/assets/silent-refresh.html"
        - name: APP_CONFIG_OAUTH2_REDIRECT_LOGIN
          value: "/{{ tpl .Values.frontend.basepath .}}"
        - name: APP_CONFIG_OAUTH2_REDIRECT_LOGOUT
          value: "/{{ tpl .Values.frontend.basepath .}}"
{{- end }}
        - name: API_PATH_PREFIX
          value: "{{ .Values.backend.prefix }}"
{{ include "activiti-cloud-modeling.extra-env-frontend" . | indent 8 }}
        ports:
        - containerPort: {{ .Values.service.frontend.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ tpl .Values.frontend.probePath . }}
            port: {{ .Values.service.frontend.internalPort }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ tpl .Values.frontend.probePath . }}
            port: {{ .Values.service.frontend.internalPort }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
        resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- if .Values.extraVolumes }}
      volumes:
{{- with .Values.extraVolumes }}
{{ tpl . $ | indent 8 }}
{{- end }}
{{- end }}
