dependencies:
  - name: activiti-cloud-query
    repository: https://kaimeng.github.io/helm-repo
    version: 0.0.1
    condition: application.activiti-cloud-query.enabled,activiti-cloud-query.enabled
  - name: activiti-cloud-audit
    repository: https://kaimeng.github.io/helm-repo
    version: 0.0.1
    condition: application.activiti-cloud-audit.enabled,activiti-cloud-audit.enabled
  - alias: rabbitmq
    name: rabbitmq-ha
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.19.0
    condition: application.rabbitmq.enabled,rabbitmq.enabled
  - alias: postgres
    name: postgresql
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 3.11.3
    condition: application.postgres.enabled,postgres.enabled
  - name: activiti-cloud-events-adapter
    repository: https://kaimeng.github.io/helm-repo
    version: 0.0.1
    condition: application.activiti-cloud-events-adapter.enabled,activiti-cloud-events-adapter.enabled
  - name: activiti-cloud-notifications-graphql
    repository: https://kaimeng.github.io/helm-repo
    version: 0.0.1
    condition: application.activiti-cloud-notifications-graphql.enabled,activiti-cloud-notifications-graphql.enabled
  