activiti-cloud-events-adapter:
  enabled: false

activiti-cloud-query:
  enabled: true
  postgres:
    enabled: true

activiti-cloud-audit:
  enabled: true
  postgres:
    enabled: true

activiti-cloud-demo-ui:
  enabled: false

runtime-bundle:
  enabled: true
  postgres:
    enabled: true

activiti-cloud-connector:
  enabled: false

activiti-cloud-notifications-graphql:
  enabled: true
  postgres:
    enabled: true

postgres:
  enabled: true
  postgresqlPassword: password
  resources:
    requests:
      cpu: 350m
      memory: 512Mi

rabbitmq:
  enabled: true
  service:
    clusterIP: None
  persistentVolume:
    enabled: true    
  rabbitmqUsername: "guest"
  rabbitmqPassword: "guest"
  rabbitmqErlangCookie: 124567890abcdefghijklmnopqrstuv
  rabbitmqSTOMPPlugin:
    enabled: true
  resources:
   limits:
    cpu: 1
    memory: 2Gi
   requests:
    cpu: 350m
    memory: 512Mi
  rbac:
    create: true
  replicaCount: 1
  ingress:
    enabled: false
#    hostName: "rabbitmq.jx-staging.X.X.X.X.nip.io"
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
